version: '3.9'

services:
  api_gateway:
    container_name: api_gateway
    build: .
    ports:
      - "9000:9000"
    networks:
      - GLhost

networks:
  GLhost:
    external: true
    name: home
    driver: bridge

  mynetwork:
    driver: bridge

volumes:
  db:
