version: '3.9'

services:
  auth_service:
    container_name: auth_service
    build: .
    ports:
      - "8001:8001"
    networks:
      - GLhost

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - GLhost


networks:
  GLhost:
    external: true
    name: home
    driver: bridge

  mynetwork:
    driver: bridge

volumes:
  db:
